### ISSUE TITLE
BaiDu  里的 selectImg 这个方法是做什么用的？  

### ISSUE THREAD

**Issue by rupertqin** [wuchangfeng/Crawler#3]
运行了没什么用，看代码也看不出来什么

**Comment by wuchangfeng** [comment]
https://github.com/wuchangfeng/Crawler/blob/master/BaiDu/GetPicture.py#L109

是说这里是吧？由于下载了得图片尺寸大小不一样。而当时下载这些图片想要一些同样大小尺寸得图片，也就是讲如果尺寸不符合自己的目的，就选择删除，留下来的就是我想要的图片。
